/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.risc.team11;

public class Risc {

    public static void main(String[] args) {
        System.out.println(
                "Use \"gradle -PmainClass=ece651.risc.team11.RiscServer run\" to run the server.");
        System.out.println("\tor");
        System.out.println(
                "Use \"gradle -PmainClass=ece651.risc.team11.RiscGUIClient run\" to run the client.");
    }
}